seed = 1
parent_dir = "exp/cidds"
real_data_path = "data/cidds/"
data_name = "cidds"
model_type = "mlp"
num_numerical_features = 6
device = "cuda"
cat_encoding = 'onehot'
num_encoding = 'quantized'

[model_params]
num_classes = 2
is_y_cond = true

[model_params.rtdl_params]
d_layers = [
    512,
    1024,
    1024,
    1024,
    1024,
    512,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 100
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 50000
lr = 0.0002
weight_decay = 0.0
batch_size = 4096
