seed = 1
parent_dir = "exp/erp_normal2/ddpm_erp_best"
real_data_path = "data/erp_fraud/"
data_name = "erp"
model_type = "mlp"
num_numerical_features = 10
device = "cuda"
cat_encoding = "ordinal"
num_encoding = "quantized"

[model_params]
num_classes = 2
is_y_cond = true

[model_params.rtdl_params]
d_layers = [
    256,
    512,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 250
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 20000
lr = 0.00026521248231055274
weight_decay = 0.0
batch_size = 4096
